Default view for no data show
featureform/embeddinghub pull request #146
Opened 2022-02-02 04:25 UTC by Sami1309

2022-02-02 04:44 UTC, Sami1309 commented
![image](https://user-images.githubusercontent.com/5938994/152094375-672524e0-1cda-4289-b844-c9c90e839067.png)
Current appearance

2022-02-08 23:26 UTC, simba-git requested changes

2022-02-08 23:26 UTC, simba-git commented on dashboard/package.json
> +    "start_empty": "set REACT_APP_EMPTY_RESOURCE_VIEW=true && set PORT=8000 && react-scripts start",
This is windows specific

2022-02-08 23:26 UTC, simba-git commented on dashboard/src/components/resource-list/ResourceListView.js
>  import FormControl from "@material-ui/core/FormControl";
I realized that isLoading is broken for ResourceView because it flashes the empty resource list every time

2022-02-08 23:26 UTC, simba-git commented on dashboard/src/components/resource-list/ResourceListView.js
> +        <Typography variant="h4">No {type} Registered</Typography>
Let's use pluralize to make this plural

2022-02-08 23:26 UTC, simba-git commented on dashboard/src/components/resource-list/ResourceListView.js
> +          Looks like your organization hasn't registered one{" "}
There are no visible Xs in your organization. Check out our docs for step by step instructions to create one.

2022-02-09 00:51 UTC, simba-git requested changes

2022-02-09 00:51 UTC, simba-git commented on dashboard/package.json
>      "build": "set PORT=8000 && react-scripts build",
Don't forget to do the above

2022-02-09 00:51 UTC, simba-git commented on dashboard/src/api/resources/Resources.js
> +    if (process.env.REACT_APP_EMPTY_RESOURCE_VIEW == "true ") {
Space after true

2022-02-09 00:51 UTC, simba-git commented on dashboard/package.json
> +    "react-pluralize": "^1.6.3",
remove

2022-02-09 00:51 UTC, simba-git commented on dashboard/package.json
> +    "run-script-os": "^1.1.6"
move to devDependencies and remove the comma above

2022-02-09 00:59 UTC, simba-git approved these changes

2022-02-09 01:11 UTC, merged