Feature/etcd lookup/sterling
featureform/embeddinghub pull request #191
Opened 2022-03-24 17:15 UTC by sdreyer

2022-03-24 20:04 UTC, Sami1309 reviewed
Looks very good imo

2022-03-24 20:37 UTC, sdreyer commented on ff/serving/metadata/etcd.go
> +func (config EtcdConfig) GetCountWithPrefix(key string) (int64, error) {
good point

2022-03-25 16:02 UTC, simba-git requested changes
Really excited to get this in, few minor changes

2022-03-25 19:06 UTC, sdreyer commented on ff/serving/go.mod
>  require (
Removed it. Should add a gitignore on that file

2022-03-25 19:09 UTC, sdreyer commented on ff/serving/metadata/etcd.go
> +	if !resType.Proto().ProtoReflect().IsValid() {
Yeah, was getting null pointer exceptions when testing it with empty resources

2022-03-25 19:12 UTC, sdreyer commented on ff/serving/metrics/test/metrics_test.go
Can revert it. Just got caught in gofmt

2022-03-25 20:00 UTC, sdreyer commented on ff/serving/metadata/metadata.go
> +	if err := lookup.Set(res.ID(), res); err != nil {
gotcha

2022-03-25 20:47 UTC, sdreyer commented on ff/serving/metadata/metadata.go
> +	StorageProvider StorageProvider
you go it

2022-03-25 20:49 UTC, sdreyer commented on ff/serving/metrics/test/metrics_test.go
Reverted

2022-03-25 20:50 UTC, sdreyer commented on ff/serving/metadata/etcd.go
> +	Host string //localhost
Removed

2022-03-25 20:50 UTC, sdreyer commented on ff/serving/metadata/etcd.go
> +	p, _ := proto.Marshal(res.Proto())
Likely was testing something and forgot to put it back. Readded

2022-03-25 20:51 UTC, sdreyer commented on ff/serving/metadata/etcd.go
> +	strmsg, err := json.Marshal(msg)
Changed Name

2022-03-25 20:51 UTC, sdreyer commented on ff/serving/metadata/etcd.go
> +func (lookup etcdResourceLookup) findResourceType(t ResourceType) (Resource, error) {
Renamed to createEmptyResource for clarity

2022-03-25 20:53 UTC, sdreyer commented
Need to fix that coverage test. Actual test coverage is ~80%

2022-03-26 00:20 UTC, simba-git submitted a review, later dismissed

2022-03-26 00:25 UTC, merged